site_name: School of Titans
repo_url: https://github.com/fszale/school-of-titans
site_author: Filip Szalewicz

theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
plugins:
  - search
nav:
  - Home: index.md
  - Start Here: start.md
  - Tools of Titans: tools.md
  - Future Trends: trends.md
  - Engineering: engineering.md
  - Sources: sources.md
  - About: about.md
